/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:941595:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:941595:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:874609:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:874609:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("TIN-H");
  button1 = new GButton(this, 26, 34, 237, 104);
  button1.setIcon("Screenshot_1.png", 1, GAlign.EAST, GAlign.LEFT, GAlign.TOP);
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 294, 34, 167, 104);
  button2.setIcon("Screenshot_2.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  button2.setLocalColorScheme(GCScheme.RED_SCHEME);
  button2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 